name: CI Build

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    # Step 1: Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Step 2: install the Python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt

    # Step 3: Lint with flake8
    - name: Lint with flake8
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

    # Step 4: Run unit tests with Nose
    - name: Run unit tests with Nose
      run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=service
      env:
        DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
